// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RealEstateManagement.Data.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class RentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Landlord",
                            NormalizedName = "LANDLORD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Renter",
                            NormalizedName = "RENTER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Air Conditioning",
                            Name = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-speed Internet",
                            Name = "WiFi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Parking Space",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Private Balcony",
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("renter");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bc2c33c-5105-41a1-a1fa-b5f50c90bd2f",
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 4, 937, DateTimeKind.Local).AddTicks(3431),
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            IsVerified = true,
                            LockoutEnabled = false,
                            Name = "Admin User",
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAdQ3GcqKl4hiJyazKCbP781Mm6Iyi4lABQpoE+weyMsdJVNeI5PcHHGk5S7oRWpOw==",
                            PhoneNumber = "12345678910",
                            PhoneNumberConfirmed = true,
                            Role = "admin",
                            SecurityStamp = "2964c865-3e01-40d2-a0c8-e917fdd78c13",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95ca33f1-b0fa-4e34-956f-2b7b600bf0e4",
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 4, 989, DateTimeKind.Local).AddTicks(4032),
                            Email = "landlord@example.com",
                            EmailConfirmed = false,
                            IsVerified = true,
                            LockoutEnabled = false,
                            Name = "Landlord User",
                            NormalizedEmail = "LANDLORD@EXAMPLE.COM",
                            NormalizedUserName = "LANDLORD@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAyjj13yOAcbkao2PhJG4yLfgtD2c7Quqfk18ftlkL6d3thdN48pJs1pV+ddo4smcg==",
                            PhoneNumber = "02345678910",
                            PhoneNumberConfirmed = true,
                            ProfilePictureUrl = "https://th.bing.com/th/id/R.63d31ac6257157ef079f31bb32e342df?rik=63%2bkafQNo5seHg&pid=ImgRaw&r=0",
                            Role = "landlord",
                            SecurityStamp = "822a5969-cdeb-492c-955e-cc8b79716e0f",
                            TwoFactorEnabled = false,
                            UserName = "landlord@example.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3056b100-653c-4435-8e94-4933d64547c9",
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 46, DateTimeKind.Local).AddTicks(7894),
                            Email = "renter@example.com",
                            EmailConfirmed = false,
                            IsVerified = true,
                            LockoutEnabled = false,
                            Name = "Renter User",
                            NormalizedEmail = "RENTER@EXAMPLE.COM",
                            NormalizedUserName = "RENTER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECYaA1kTW+AdxJoOLdckkUbRF5Puw9SALJopfwgPLk2RJ3JagGZrg0pw0lxxSvup/A==",
                            PhoneNumber = "03345678910",
                            PhoneNumberConfirmed = true,
                            Role = "renter",
                            SecurityStamp = "14aaa72e-484e-4fdd-a04b-4993bef3201d",
                            TwoFactorEnabled = false,
                            UserName = "renter@example.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c198d973-8480-4036-a948-f931661a1806",
                            CreatedAt = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(2502),
                            Email = "renter2@example.com",
                            EmailConfirmed = false,
                            IsVerified = true,
                            LockoutEnabled = false,
                            Name = "Renter User 2",
                            NormalizedEmail = "RENTER2@EXAMPLE.COM",
                            NormalizedUserName = "RENTER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCJwKC6rM5KY71IGOxVvHUYiJKaMhmZejbL1q9epxhY+xPY/gAf4auhiUvfkfpS3w==",
                            PhoneNumberConfirmed = false,
                            Role = "renter",
                            SecurityStamp = "bdb44cb6-6415-4144-ae14-47f136aa23f3",
                            TwoFactorEnabled = false,
                            UserName = "renter2@example.com"
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RenterId");

                    b.ToTable("Conversation");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000000m,
                            ContractId = 1,
                            PaidAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3455),
                            PaymentMethod = "Momo",
                            Status = "completed",
                            TransactionId = 1
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PromotionPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("promotionPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3637),
                            Description = "Basic promotion package for property listings.",
                            DurationInDays = 30,
                            IsActive = true,
                            Level = 1,
                            Name = "Basic Promotion",
                            Price = 1000000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3639),
                            Description = "Premium promotion package for property listings.",
                            DurationInDays = 60,
                            IsActive = true,
                            Level = 2,
                            Name = "Premium Promotion",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3641),
                            Description = "Ultimate promotion package for property listings.",
                            DurationInDays = 90,
                            IsActive = true,
                            Level = 3,
                            Name = "Ultimate Promotion",
                            Price = 3000000m
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPromoted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyen Hue, District 1, HCMC",
                            Area = 50.5m,
                            Bedrooms = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3199),
                            Description = "Modern apartment with 2 bedrooms in the heart of HCMC.",
                            IsPromoted = false,
                            IsVerified = true,
                            LandlordId = 2,
                            Location = "10.7769,106.7009",
                            Price = 5000000m,
                            Status = "available",
                            Title = "2BR Apartment in District 1",
                            Type = "apartment",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Le Van Tho, Go Vap, HCMC",
                            Area = 20.0m,
                            Bedrooms = 1,
                            CreatedAt = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3206),
                            Description = "Cozy shared room for students.",
                            IsPromoted = false,
                            IsVerified = true,
                            LandlordId = 2,
                            Location = "10.8505,106.6737",
                            Price = 2000000m,
                            Status = "available",
                            Title = "Shared Room in Go Vap",
                            Type = "room",
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Ly Thuong Kiet, Tan Binh, HCMC",
                            Area = 80.0m,
                            Bedrooms = 3,
                            CreatedAt = new DateTime(2025, 6, 16, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3209),
                            Description = "Spacious house with 3 bedrooms.",
                            IsPromoted = true,
                            IsVerified = true,
                            LandlordId = 2,
                            Location = "10.7982,106.6582",
                            Price = 8000000m,
                            Status = "available",
                            Title = "3BR House in Tan Binh",
                            Type = "house",
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            PropertyId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            PropertyId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 3,
                            AmenityId = 4
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            Order = 1,
                            PropertyId = 1,
                            Url = "https://example.com/apartment1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = false,
                            Order = 2,
                            PropertyId = 1,
                            Url = "https://example.com/apartment2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = true,
                            Order = 1,
                            PropertyId = 2,
                            Url = "https://example.com/room1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = true,
                            Order = 1,
                            PropertyId = 3,
                            Url = "https://example.com/house1.jpg"
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("PropertyPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3394),
                            LandlordId = 2,
                            PropertyId = 1,
                            Status = "Approved",
                            VerifiedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3408),
                            VerifiedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3412),
                            LandlordId = 2,
                            PropertyId = 2,
                            Status = "Approved",
                            VerifiedAt = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3412),
                            VerifiedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 16, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3414),
                            LandlordId = 2,
                            PropertyId = 3,
                            Status = "Approved",
                            VerifiedAt = new DateTime(2025, 6, 16, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3415),
                            VerifiedBy = 1
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyPromotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 7, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3674),
                            PackageId = 1,
                            PropertyId = 1,
                            StartDate = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3674)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 7, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3676),
                            PackageId = 2,
                            PropertyId = 2,
                            StartDate = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3676)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 9, 14, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3678),
                            PackageId = 3,
                            PropertyId = 3,
                            StartDate = new DateTime(2025, 6, 16, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3677)
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.RentalContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ContractDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropertyPostId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyPostId1")
                        .HasColumnType("int");

                    b.Property<int?>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PropertyPostId")
                        .IsUnique();

                    b.HasIndex("PropertyPostId1")
                        .IsUnique()
                        .HasFilter("[PropertyPostId1] IS NOT NULL");

                    b.HasIndex("RenterId");

                    b.ToTable("RentalContracts");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RenterId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating_Range", "Rating BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great location and clean apartment!",
                            CreatedAt = new DateTime(2025, 6, 17, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3566),
                            IsApproved = true,
                            PropertyId = 1,
                            Rating = 4,
                            RenterId = 3
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000000m,
                            CreatedAt = new DateTime(2025, 6, 18, 2, 18, 5, 104, DateTimeKind.Local).AddTicks(3516),
                            Description = "Deposit for apartment in District 1",
                            TransactionType = "deposit",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.UserFavoriteProperty", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId");

                    b.ToTable("UserFavoriteProperties");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PriceRangeMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceRangeMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Conversation", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Landlord")
                        .WithMany("ConversationsAsLandlord")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("Conversations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Renter")
                        .WithMany("ConversationsAsRenter")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Message", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Payment", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Transaction", "Transaction")
                        .WithMany("Payments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Property", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyAmenity", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyImage", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyPost", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("Posts")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyPromotion", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.PromotionPackage", "PromotionPackage")
                        .WithMany("PropertyPromotions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("PropertyPromotions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionPackage");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.RentalContract", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.PropertyPost", "PropertyPost")
                        .WithOne()
                        .HasForeignKey("RealEstateManagement.Data.Entity.RentalContract", "PropertyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.PropertyPost", null)
                        .WithOne("RentalContract")
                        .HasForeignKey("RealEstateManagement.Data.Entity.RentalContract", "PropertyPostId1");

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Landlord");

                    b.Navigation("PropertyPost");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Review", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "Renter")
                        .WithMany("Reviews")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Transaction", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.UserFavoriteProperty", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.Property", "Property")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "User")
                        .WithMany("FavoriteProperties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.UserPreference", b =>
                {
                    b.HasOne("RealEstateManagement.Data.Entity.ApplicationUser", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.ApplicationUser", b =>
                {
                    b.Navigation("ConversationsAsLandlord");

                    b.Navigation("ConversationsAsRenter");

                    b.Navigation("FavoriteProperties");

                    b.Navigation("MessagesSent");

                    b.Navigation("Preferences");

                    b.Navigation("Properties");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PromotionPackage", b =>
                {
                    b.Navigation("PropertyPromotions");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Property", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("Images");

                    b.Navigation("Posts");

                    b.Navigation("PropertyAmenities");

                    b.Navigation("PropertyPromotions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.PropertyPost", b =>
                {
                    b.Navigation("RentalContract")
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateManagement.Data.Entity.Transaction", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
